Traceback (most recent call last):
  File "/Users/maurini/anaconda3/envs/mu4mes03/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/maurini/anaconda3/envs/mu4mes03/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/maurini/anaconda3/envs/mu4mes03/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/maurini/anaconda3/envs/mu4mes03/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/maurini/anaconda3/envs/mu4mes03/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/maurini/anaconda3/envs/mu4mes03/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/maurini/anaconda3/envs/mu4mes03/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/maurini/anaconda3/envs/mu4mes03/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def U_elem(U,e):
    """ Returns the element local values in global coordinates"""
    glob_dofs = global_dofs_element(e)
    return U.take(glob_dofs)

def U_elem_loc(U,e):
    """ Returns the element local values in local coordinates"""
    T_mat = T.transpose().subs({alpha:alphas[e]})
    return  np.dot(T_mat, U_elem(U,e))

def U_node(U,n):
    """ Returns the displacement of a node"""
    return U.take([3 * n, 3 * n + 1])

U_elem(U,1)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[20], line 15[0m
[1;32m     12[0m [38;5;250m    [39m[38;5;124;03m""" Returns the displacement of a node"""[39;00m
[1;32m     13[0m     [38;5;28;01mreturn[39;00m U[38;5;241m.[39mtake([[38;5;241m3[39m [38;5;241m*[39m n, [38;5;241m3[39m [38;5;241m*[39m n [38;5;241m+[39m [38;5;241m1[39m])
[0;32m---> 15[0m [43mU_elem[49m[43m([49m[43mU[49m[43m,[49m[38;5;241;43m1[39;49m[43m)[49m

Cell [0;32mIn[20], line 3[0m, in [0;36mU_elem[0;34m(U, e)[0m
[1;32m      1[0m [38;5;28;01mdef[39;00m [38;5;21mU_elem[39m(U,e):
[1;32m      2[0m [38;5;250m    [39m[38;5;124;03m""" Returns the element local values in global coordinates"""[39;00m
[0;32m----> 3[0m     glob_dofs [38;5;241m=[39m [43mglobal_dofs_element[49m[43m([49m[43me[49m[43m)[49m
[1;32m      4[0m     [38;5;28;01mreturn[39;00m U[38;5;241m.[39mtake(glob_dofs)

Cell [0;32mIn[15], line 6[0m, in [0;36mglobal_dofs_element[0;34m(element)[0m
[1;32m      1[0m [38;5;28;01mdef[39;00m [38;5;21mglobal_dofs_element[39m(element):
[1;32m      2[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[1;32m      3[0m [38;5;124;03m    Returns the global dof numbers given the element [39;00m
[1;32m      4[0m [38;5;124;03m    (as a pair of node numbers) [39;00m
[1;32m      5[0m [38;5;124;03m    """[39;00m
[0;32m----> 6[0m     node_0 [38;5;241m=[39m [43melement[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m 
[1;32m      7[0m     node_L [38;5;241m=[39m element[[38;5;241m1[39m] 
[1;32m      8[0m     [38;5;66;03m# global dofs number for the element vector[39;00m

[0;31mTypeError[0m: 'int' object is not subscriptable
TypeError: 'int' object is not subscriptable

