Traceback (most recent call last):
  File "/Users/maurini/anaconda3/envs/mu4mes03/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/maurini/anaconda3/envs/mu4mes03/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/maurini/anaconda3/envs/mu4mes03/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/maurini/anaconda3/envs/mu4mes03/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/maurini/anaconda3/envs/mu4mes03/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/maurini/anaconda3/envs/mu4mes03/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/maurini/anaconda3/envs/mu4mes03/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/maurini/anaconda3/envs/mu4mes03/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import sympy
Ue_values = np.array([1,0,0,0,0,0])
pl = sympy.plot_parametric(s + usol.rhs.subs({u0:bcs[0],uL:bcs[3],L:1}),
                           vsol.rhs.subs({v0:bcs[1], vL:bcs[4], theta0:bcs[2], thetaL:bcs[5],L:1}),
                           (s,0,1),
                           xlabel="x",
                           ylabel="y",
                           title=f"Deformed shape for $U_e=${bcs}")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[6], line 3[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01msympy[39;00m
[1;32m      2[0m Ue_values [38;5;241m=[39m np[38;5;241m.[39marray([[38;5;241m1[39m,[38;5;241m0[39m,[38;5;241m0[39m,[38;5;241m0[39m,[38;5;241m0[39m,[38;5;241m0[39m])
[0;32m----> 3[0m pl [38;5;241m=[39m sympy[38;5;241m.[39mplot_parametric(s [38;5;241m+[39m usol[38;5;241m.[39mrhs[38;5;241m.[39msubs({u0:[43mbcs[49m[[38;5;241m0[39m],uL:bcs[[38;5;241m3[39m],L:[38;5;241m1[39m}),
[1;32m      4[0m                            vsol[38;5;241m.[39mrhs[38;5;241m.[39msubs({v0:bcs[[38;5;241m1[39m], vL:bcs[[38;5;241m4[39m], theta0:bcs[[38;5;241m2[39m], thetaL:bcs[[38;5;241m5[39m],L:[38;5;241m1[39m}),
[1;32m      5[0m                            (s,[38;5;241m0[39m,[38;5;241m1[39m),
[1;32m      6[0m                            xlabel[38;5;241m=[39m[38;5;124m"[39m[38;5;124mx[39m[38;5;124m"[39m,
[1;32m      7[0m                            ylabel[38;5;241m=[39m[38;5;124m"[39m[38;5;124my[39m[38;5;124m"[39m,
[1;32m      8[0m                            title[38;5;241m=[39m[38;5;124mf[39m[38;5;124m"[39m[38;5;124mDeformed shape for $U_e=$[39m[38;5;132;01m{[39;00mbcs[38;5;132;01m}[39;00m[38;5;124m"[39m)

[0;31mNameError[0m: name 'bcs' is not defined
NameError: name 'bcs' is not defined

